apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: $(cat certs/server.crt | base64 | tr -d '\n')
  tls.key: $(cat certs/server.key | base64 | tr -d '\n')
